class addData():
    name = "Syarif Ridhohidayatulloh"
    city = "Purwokerto"
    pCode = "53151"
    phone = "12345"
    address = "Baturraden"
    state = "Purwokerto"
    # country = "sudah masuk dalam element.py"
    fax = "51231"
    notes = "Iniasdasd"
