class element():
    username = "username"
    password = "password"
    login_btn = "orangehrm-login-button"
    header = "//div[@id='app']//div[@class='oxd-layout-container']"
    PIM = "PIM"
    employee_list = "Employee List"
    search_employee_by_name = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/div/div/input"
    search_button = ".orangehrm-left-space.oxd-button.oxd-button--medium.oxd-button--secondary"
    search_employee_by_Id =  ".orangehrm-full-width-grid.oxd-grid-4 .oxd-input"
    select_employment_status = "/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[3]/div/div[2]/div/div[1]"
    employee_information = "/html/body/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]"
    select_full_time_contract = "/html/body/div[1]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[3]/div/div[2]/div/div[2]/div[3]/span[text()='Full-Time Contract']"
    select_job_title = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[6]/div/div[2]/div/div/div[1]"
    select_chief_executive_officer = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[6]/div/div[2]/div/div/div[2]/span[text()='Chief Executive Officer']"
    employee_list_table ="/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]"
    select_sub_unit = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[7]/div/div[2]/div/div/div[1]"
    select_OrangeHRM = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[7]/div/div[2]/div/div/div[2]/span[text()='OrangeHRM']"
    employee_sub_unit_table = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]"
    reset_button = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[2]/button[1]"
    reset_employee_name = "//div[@id='app']//div[@class='oxd-table-filter']/div[@class='oxd-table-filter-area']/form[@class='oxd-form']/div[@class='oxd-form-row']/div/div[1]/div//input[@placeholder='Type for hints...']"
    add_button = ".orangehrm-header-container .oxd-button--secondary"
    first_name = "firstName"
    middle_name = "middleName"
    last_name = "lastName"
    save_button = "button.oxd-button.oxd-button--medium.oxd-button--secondary"
    employee_not_found = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[2]/div/span"
   